#!/usr/bin/env python3
import json
import subprocess

import argparse

YABAI = '/opt/homebrew/bin/yabai'

def run(cmd: str):
    return subprocess.run(cmd, shell=True, capture_output=True).stdout

def run_json(cmd: str):
    return json.loads(run(cmd))

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('app')
    args = parser.parse_args()

    scratchpad = 6

    windows = run_json(f'{YABAI} -m query --windows')
    for window in windows:
        if window['app'] == args.app:
            break
    else:
        exit(1)

    if window['is-floating'] == False:
        run(f'{YABAI} -m window {window["id"]} --toggle float')

    if window['is-visible']:
        # if visible, hide it to scratchpad workspace
        run( f'{YABAI} -m window {window["id"]} --space {scratchpad}')
    else:
        # otherwise pull to current workspace and focus
        run(f'{YABAI} -m window {window["id"]} --space mouse && '
            f'{YABAI} -m window {window["id"]} --grid 10:10:1:1:8:8 &&'
            f'{YABAI} -m window --focus {window["id"]}')


if __name__ == '__main__':
    main()
