#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# start hotkey daemon
brew services restart skhd 
# status bar daemon
brew services restart spacebar
# start window bordering daemon
brew services restart limelight

# let Anki float
yabai -m rule --add app="^(Anki)$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Preview$" manage=off

# window focus follows mouse
yabai -m config mouse_follows_focus on
# move window with mouse
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# floating windows always on top
yabai -m config window_topmost on

# only floating windows have shadow decorations
yabai -m config window_shadow float

# global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

#https://github.com/koekeishiya/yabai/issues/830#issuecomment-774863083
yabai -m config external_bar all:32:0

# https://github.com/koekeishiya/yabai/issues/692
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
